# **Slip 04 - Data Mining**


*Q1. Write a R program to calculate the sum of two matrices of given size.         [10 Marks]*

In [ ]:
m1 <- matrix(c(1, 2, 3, 4, 5, 6), nrow = 2, ncol = 3, byrow = TRUE)
m2 <- matrix(c(6, 5, 4, 3, 2, 1), nrow = 2, ncol = 3, byrow = TRUE)

cat("\nFirst Matrix:\n")
print(m1)
cat("\nSecond Matrix:\n")
print(m2)
cat("\nSum of Matrices:\n")
print(m1 + m2)


First Matrix:
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6

Second Matrix:
     [,1] [,2] [,3]
[1,]    6    5    4
[2,]    3    2    1

Sum of Matrices:
     [,1] [,2] [,3]
[1,]    7    7    7
[2,]    7    7    7


*Q2. Co*nsider the following dataset:

```python
weather = ['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
           'Rainy','Sunny','Overcast','Overcast','Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool',
        'Mild','Mild','Mild','Hot','Mild']

play = ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes',
        'Yes','Yes','Yes','No']


Use Naïve Bayes algorithm to predict [0: Overcast, 2: Mild] tuple belongs to which class 
whether to play the sports or not.


In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB

weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy', 'Rainy', 'Overcast', 'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
temp = ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild']
play = ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

LE = LabelEncoder()
w = LE.fit_transform(weather)
t = LE.fit_transform(temp)
p = LE.fit_transform(play)

X = list(zip(w, t))
Y = p

classifier = GaussianNB()
classifier.fit(X, Y)

y_pred = classifier.predict([[0, 2]])

print("Prediction Value: ", y_pred)


Prediction Value:  [1]
